### PR TITLE
Issue #83 Encoding handling broken when doing <anysource>-to-scalar[a…

### PR DESCRIPTION
**Pull request by kenneth-olwing**
…rray] tiyding.

- Added encoding when calling ::perltidy() using a scalar/array destination.
- Added test cases to verify 'passthrough' when no tidying should be necessary
- Added test cases to verify tidying retain encoding
- Adjusted the current testwide.t as it used to pass, but for the wrong reasons

### CODE REVIEW

**Comment by kenneth-olwing** [comment]
Some notes...

Arguably, it can be done slightly cleaner, but I followed the current style when adding the necessary code; hope it's ok for you.

As noted, I've added test cases for this. However, also note that after applying my fixes the old t/testwide.t *failed*. I believe it's a matter of it previously sort of testing things using Perl magic, and getting a false positive. In my tests I'm trying to test more succinctly by checking the byte hex values of the resulting strings to make sure they're identical on the byte level. Please tell me if you feel this was an incorrect analysis.

I also noted that while the flag -enc= allows the source to have any encoding, the *destination* encoding is always forced to UTF-8 if any encoding was set (in streamhandle()), which is wrong IMO; it should use the same encoding in both places. I elected to keep this type of behavior in my fix as I didn't want to go to far. Also, I actually have no idea whether tidying would work properly for more arcane (at least to me) encodings so presumably UTF-8 is the most typical anyway. But this is a possible problem.

I hope this is satisfactory,

ken1

**Comment by shancock9** [comment]
Hi Ken,
Thanks again for working on this problem. I want to get Code::TidyAll working correctly.

In thinking about various data transfer scenarios, I realized that there are some significant pitfalls that have to be avoided, and that a little different approach will be needed.

The basic thing that must be absolutely avoided is the possibility that a perl string can get encoded more than once.  If this were to happen then the data can be badly corrupted. This is my "nightmare" scenario.  To check this, I took the string in our test file and encoded it multiple times. Each time the encoding gave no error flag but the size of the string basically doubled and became garbage.

To avoid this scenario we must only encode when a string reaches the end of its life as a perl string.  We know that this happens when the string is written to a file, so it is always ok to encode at that point.  But if a string is being returned to a calling program, we really don't know if it is at the end of its life as a perl string, and that's a problem.  So right now, the tacit assumption in Perl::Tidy is basically this:

CURRENT HIDDEN ASSUMPTION:  "Whoever writes the file does the encoding".

That's safe as far as the possibility of double encoding goes, but it's a problem for a calling program like TidyAll, which shouldn't have to deal with encoding since it doesn't know what the decoding was.  But this assumption allows perltidy to iterations internally, and to do any pre- and post-filtering on string buffers without the possibility of multiple encoding ( I think the update as written would run into problems with -iterations=2 for example).

Another possible assumption would be:

ALTERNATE ASSUMPTION: "Whoever does the decoding does encoding"

That would solve the problem we have with TidyAll, but unfortunately we can't just change perltidy to do that because it will undoubtedly break a lot of existing programs which are built on the assumption that they will receive an (unencoded) perl string or string reference for further processing, and possible later terminal encoding.

For example, a user may have written a program similar to TidyAll which reads a file, unencodes and/or decrypts in a custom way, then receives a string back from perltidy and reencodes and/or encrypts and writes to storage.

Or a user may have written a program which calls perltidy to read, decode and process a certain file, but he/she may want to receive an unencoded perl string for manipulating further with perl.  That program would corrupt its data if we change the default behavior.

So, if we can't change the default behavior because it would break programs and worse, corrupt data, what can we do?  It looks like we have to introduce a new flag to specify what to do about encoding of string output, but only if it was decoded by perltidy.  I don't know what to call it, but maybe

--encode-decoded-strings 

It could even have an alias name --tidyall to help clarify things for everybody. I kind of like that.

The logic might be something like:

- if (! --encoded-decoded-strings ) then strings are never encoded, as in the current default
- else if (perltidy decoded the input AND the output is a string or string ref) then
   perltidy encodes the string or string ref

This string encoding would only be done once, at the very end of processing (maybe in sub Exit).

That looks like it would basically work.  But there's still a little problem.  Ideally, this would a new parameter passed to Perl::Tidy by the calling program.  But this means that a program like TidyAll would have to be patched to make this work.  So to give users immediate access to this update this could also be one of the main perltidy parameters.  Then, if it was set in either .perltidyrc or by the caller to Perl::Tidy it would apply.
 
It might also be worth considering returning to the caller information about what decoding was done, if any, and what encoding was done, if any.  I need to think about that.

As far as encoding in something other than utf8, that has been left as a future possibility but nobody has ever requested it. It seems that the perl world is mainly in utf8. I put in the ability to decode from any encoding mainly for testing purposes.

Let me know if you see problems with this approach.  Decoding and encoding are not my favorite things to work on.

Why don't we do this: I will try to put together something like the above logic over the next few weeks, and then if you have time you can rework your test program with the new flag and see if you can get TidyAll working, making any necessary changes.


Thanks again,
Steve

**Comment by kenneth-olwing** [comment]
Hi Steve, thanks for your effort on this, and most certainly, your 
longtime effort with P::T!

FIrst, I want to say that I basically agree with your assessment on why 
the proposed change may not be the best way forward. I never considered 
the 'multiple iterations' thing, and also, I agree on the issue of 
backwards compatibility in general - a package going on 21 years must 
certainly be respected :-)!

So, at this point, let's not do anything that you don't feel confident 
in. For my current situation, I do have an acceptable workaround: I 
simply created my own PerlTidy plugin to C::T by taking the original and 
changing it so it doesn't pass in a destination scalar. Instead, I 
create a tmp file, pass in that as the destination, let P::T::perltidy() 
do it's thing, slurp_raw it back into my destination variable and pass 
that back. Obviously a bit clumsy/heavy-handed but as 'writing to file' 
using the -utf8 plag is known to work, this does what I need. Obviously 
it also adds some overhead, but generally speaking, negligible (for me). 
In principle, it would obviously also be possible to submit a patch for 
C::T along these lines if push comes to shove. In any case, I can wait 
for a better fix.

However. I'm not certain I believe in your thoughts on how to 
proceed...:-/. Certainly, as I said, you must be comfortable with it 
going forward. And, of course, number of hours put in to make everybody 
happy :-). But here are some thoughts on general issues and possible 
alternative approaches...

Correct me if I'm wrong, but I'm assuming that when P::T was created 
there was no thought given to the necessity of encodings (or even the 
possibility). I want to be explicit here: this is no judgment or 
anything, it's just the way technology progress. Thus, when -utf8/-enc= 
was conceived it's basically a bolt on later (almost 15 years after 
initial version!) so it's quite understandable that it's tricky to 
handle all possible existing interactions with the API.

The problem now is that more generic encoding support is inarguably 
broken, beyond the UTF-8 issue. I appreciate that the -enc flag was 
added mostly for testing, but it still is described in the docs, and I 
seem to recall something to the effect of '-utf8 is equivalent to 
-enc=UTF-8'.

As I noted, one issue is that if *any* encoding is specified, it doesn't 
really matter for output - it is now hardcoded to UTF-8. In fact, it is 
easy to create a problem 'the other way': here in Sweden we typically 
use ISO-8859-1 as the 8-bit character set. Since it's still one byte, it 
allows a lot of old code to work anyway (e.g. byte oriented)...which is 
bad because it tends to hide errors when mistaking characters for bytes. 
Anyway, consider the code:

     print "Hej xxxåäöxxxÅÄÖxxx\n"

Saved as swedish.pl in ISO-8859-1. Now, a conscientious programmer like 
myself might want to go the extra mile and be certain that P::T 
understands what my data is. So:

     perltidy -enc=ISO-8859-1 swedish.pl

You already know what happens :-). My swedish.pl.tdy file now looks like 
this (using an editor or whatever that is geared for ISO-8859-1 and 
depending on what font I use and bla bla bla):

     print "Hej xxxÃ¥Ã¤Ã¶xxxÃ…Ã„Ã–xxx\n"

I.e. the output is now in UTF-8 which is nice, but certainly unexpected. 
From my POV it is now most certainly 'garbage', where all the swedish 
national characters have become variable byte length (2 bytes per 
character).

Can this be fixed? Yes, certainly - switch the hardcoded UTF-8 given to 
files for example and into actually using the -enc setting. But would 
you want to? This is also a current behavior that someone might depend 
on (very unlikely I guess, but for the sake of the argument). So exactly 
what behavior is deemed acceptable to change when it is demonstrably 
wrong/weird/unexpected...?

To summarize my assumption on P::T::perltidy(): basically whatever I 
feed into it encoding-wise, I'd expect the same encoding back. No more, 
no less.

Given the current API however, this is, as you've outlined, very 
difficult to achieve for lots of reasons. Again; from a C::T POV it is 
completely agnostic on how the input may be encoded (or not), so it'd be 
quite difficult (and weird) to try to teach it that this can happen when 
'-utf8' or '-enc=' is sent to perltidy(), and that it should somehow try 
to undo certain things then.

I believe that adding new 'workaround' flag logic to P::T to solve this 
may just twist the pretzel a bit further without really addressing the 
basic problem: the API was never designed for this type of problem and 
thus have no real way for consumer/producer to have a defined 
'guarantee' on this; instead it has the hidden/tacit assumption you mention.

So, while the current API should maybe actually stay as is for backwards 
compat, would it perhaps be reasonable to add a new API call, e.g. for 
simplicitys sake 'perltidy2()' which sort of is described as 
'encoding/decoding' aware with the guarantee listed above (encoding in 
== encoding out). Actually, the API could probably look the same, just 
that the presence of things like '-utf8' would make it 'do the right 
thing' in all places, vs calls using the 'old' API simply plods on like 
before. This could get a bit involved of course - what about the 
logfile, errorfile, teefile, debugfile? Documentation to the effect, a 
commandline flag to indicate to the command perltidy that 'API 2' is 
desired etc, with the ultimate goal of switching the defaults. The 
'-enc=' flag can stay as is - if it's solved for the specific case of 
UTF-8, it should make it no harder to handle arbitrary encodings. 
Overall, this is perhaps a lengthy and the most complex endeavor to do, 
but with the most future-proofing.

Another approach is to simply punt on the issue and just document the 
behavior clearly. Packages like C::T can be changed to suit in whatever 
manner works best - I could just supply my plugin as an alternative P::T 
plugin and document 'must be used if you want to deal with UTF-8 encoded 
files'. This approach is obviously quick and simple, but just shifts the 
problem to 'someone else' (which is the situation today, for good or bad 
:-).

Or of course to stick with your current thinking - I'm sure it can be 
made to work nicely for this issue, the bad part is that it makes the 
code a little more complex while not really solving any deeper problems. 
In case you take this route, at least I'd recommend to think about how 
to deal with '-enc=' going forward - should arbitrary encodings be 
supported or is UTF-8 the one and only?

Sorry for the length, hope this helps going forward. Also, whatever I 
can help with, please holler.

ken1

**Comment by shancock9** [comment]
Hi Ken,

I wrote an update to Tidy.pm along the lines I mentioned, and I haven't found any problems with it so I have pushed the update to github. I still have to do documentation, but basically there here is a new flag --encode-output-string, or -eos, which can be set to get perltidy to encode an output string or array reference. It keeps default behavior unchanged, and it avoids problems with things like the -conv flag.  It should fix the tidyall problem. You should just have to set -eos.  Your test programs which check actual byte input and output should work if you set this flag. 

I've done local testing of this update on my machine but haven't added any test cases yet.  You had some nice test cases.  It would be nice if you could add them (with -eos) sometime if this update works.

I'm glad perltidy has been useful. You are right, perltidy has evolved from a time when encoding/decoding were not a feature.  I haven't had time yet to go through what you've discussed on the encoding/decoding issue, but basically I'm open to any changes which might improve usfulness.  But it is essential that existing software using Perl::Tidy continues to run as expected.  I've accidentally caused software dependent on Perl::Tidy to fail in the past with very minor changes in default behavior, and it is not fun.

Thanks again for working on this,
Steve

**Comment by kenneth-olwing** [comment]
Hi Steve,

Thanks tor your work. I think we're agreed on keeping backwards compat 
so I'll give the -eos a spin and get back to you with an updated PR 
(possibly only with the tests I devised :-).

Thanks,

ken1

**Comment by shancock9** [comment]
I'm glad you concur, I'll go ahead.

**Pull request closed without merging**
